// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChpXQ0F2CEo4rBjqAMTTa0QD6TnyEP6D0',
    appId: '1:382952972400:web:ad480df9cc009609ff54b5',
    messagingSenderId: '382952972400',
    projectId: 'blindfriend-acea4',
    authDomain: 'blindfriend-acea4.firebaseapp.com',
    storageBucket: 'blindfriend-acea4.firebasestorage.app',
    measurementId: 'G-DFFQSR93RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxD5y660p_hyL3QR3J_Q02mB_TkQq5-WE',
    appId: '1:382952972400:android:c20f6bf4f7d1dcc0ff54b5',
    messagingSenderId: '382952972400',
    projectId: 'blindfriend-acea4',
    storageBucket: 'blindfriend-acea4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR7Od729J0gsWbkY5p8nGDbxNy4OzqJzk',
    appId: '1:382952972400:ios:392e3894f9d36e6dff54b5',
    messagingSenderId: '382952972400',
    projectId: 'blindfriend-acea4',
    storageBucket: 'blindfriend-acea4.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlindfriend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR7Od729J0gsWbkY5p8nGDbxNy4OzqJzk',
    appId: '1:382952972400:ios:392e3894f9d36e6dff54b5',
    messagingSenderId: '382952972400',
    projectId: 'blindfriend-acea4',
    storageBucket: 'blindfriend-acea4.firebasestorage.app',
    iosBundleId: 'com.example.flutterBlindfriend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChpXQ0F2CEo4rBjqAMTTa0QD6TnyEP6D0',
    appId: '1:382952972400:web:323bd3407ba139dcff54b5',
    messagingSenderId: '382952972400',
    projectId: 'blindfriend-acea4',
    authDomain: 'blindfriend-acea4.firebaseapp.com',
    storageBucket: 'blindfriend-acea4.firebasestorage.app',
    measurementId: 'G-8BQBLM9723',
  );
}
